### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by 11051911** [sinanugur/cellsnake#1]
Hello, when I was installing, the following error appeared, changed for a long time has not been changed, do you have any suggestions
`(base) F:\ms下载\cellsnake-main>mamba create -n cellsnake -c bioconda -c conda-forge cellsnake

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Looking for: ['cellsnake']

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "D:\anaconda3\lib\site-packages\mamba\mamba.py", line 927, in exception_converter
        raise e
      File "D:\anaconda3\lib\site-packages\mamba\mamba.py", line 921, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "D:\anaconda3\lib\site-packages\mamba\mamba.py", line 879, in _wrapped_main
        result = do_call(args, p)
      File "D:\anaconda3\lib\site-packages\mamba\mamba.py", line 761, in do_call
        exit_code = create(args, parser)
      File "D:\anaconda3\lib\site-packages\mamba\mamba.py", line 664, in create
        return install(args, parser, "create")
      File "D:\anaconda3\lib\site-packages\mamba\mamba.py", line 520, in install
        repo = api.Repo(pool, "installed", installed_json_f.name, "")
    RuntimeError: Could not open repository file C:\Users\刘天祥~1\AppData\Local\Temp\tmp4ilpz9m5

`$ D:\anaconda3\Scripts\mamba create -n cellsnake -c bioconda -c conda-forge cellsnake`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=D:\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="D:\anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=D:\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=D:\anaconda3\python.exe
               CONDA_ROOT=D:\anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\刘天祥sky
                     PATH=D:\anaconda3;D:\anaconda3\Library\mingw-w64\bin;D:\anaconda3\Library\u
                          sr\bin;D:\anaconda3\Library\bin;D:\anaconda3\Scripts;D:\anaconda3\bin;
                          D:\anaconda3;D:\anaconda3\Library\mingw-w64\bin;D:\anaconda3\Library\u
                          sr\bin;D:\anaconda3\Library\bin;D:\anaconda3\Scripts;D:\anaconda3\bin;
                          D:\anaconda3\condabin;G:\VMare16\bin;C:\Windows\system32;C:\Windows;C:
                          \Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\W
                          indows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA Nv
                          DLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDO
                          WS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Prog
                          ram Files\R\R-4.2.2\bin\x64;?C:\Program Files\RStudio\bin;.;C:\Program
                          Files\IDM Computer Solutions\UltraEdit;D:\wget;D:\ANACONDA\Library\min
                          gw-w64\bin;D:\ANACONDA\Library\usr\bin;D:\ANACONDA\Library\bin;D:\ANAC
                          ONDA\Scripts;C:\Users\閸掓ê銇夌粊顧筴y\AppData\Local\Microsoft\WindowsApps;D:
                          \pycharm\PyCharm Community Edition
                          2019.3.3\bin;.;C:\Users\閸掓ê銇夌粊顧筴y\AppData\Local\Programs\Microsoft VS
                          Code\bin;D:\LenovoSoftstore\Install\QQliuxidating\QQGameTempest\Hall.5
                          7808;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : D:\anaconda3
            shell level : 1
       user config file : C:\Users\刘天祥sky\.condarc
 populated config files : C:\Users\刘天祥sky\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.6=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : D:\anaconda3  (writable)
      conda av data dir : D:\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/win-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\anaconda3\pkgs
                          C:\Users\刘天祥sky\.conda\pkgs
                          C:\Users\刘天祥~1\AppData\Local\conda\conda\pkgs
       envs directories : D:\anaconda3\envs
                          C:\Users\刘天祥sky\.conda\envs
                          C:\Users\刘天祥~1\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
`

**Comment by sinanugur** [comment]
Thanks for your interest to Cellsnake.

I think you are using conda on Windows. Unfortunately, we have not tested Cellsnake on Windows with Conda. Most of the underlying tools are not compatible with Windows. Please try using our Docker container on Windows. It is the best solution.

https://hub.docker.com/r/sinanugur/cellsnake

We also recommend a machine with a higher memory if you prefer Docker on Windows. I keep this thread open for now. I will test conda on Windows, perhaps we can support this later.

Cheers,
@sinanugur
